### ISSUE TITLE
Android Animator Freezes UI

### ISSUE THREAD

**Issue by dmikey** [dmikey/syr#136]
BOOO.

Animations are not removed like iOS. Need to re-config the animator to keep track of animations bound to properties and components.

**Comment by pvenkatakrishnan** [comment]
😢

**Comment by dmikey** [comment]
Fixed in https://github.com/dmikey/syr/commit/917861012ba3939f7acf06d83d6ff1b5a066e80a

Add a bunch of threading, and explicitly queuing Animations on the UI thread.
